### ISSUE TITLE
View: Tracker

### ISSUE THREAD

**Issue by caseywalker** [caseywalker/Finance-Planner#27]
- [ ] Add view for Tracker.js
- [ ] useState for incomeObjects, monthly income, annual income, expenseObjects, monthly expenses, annual expenses, monthly surplus, and annual surplus
- [ ] useEffect to getIncome, store in incomeObjects
- [ ] function to iterate through each incomeObject.amount and store in monthly income state
- [ ] function to iterate through each expenseObject.amount and store in monthly expense state 
- [ ] function to multiply monthly income * 12 and store in annual income state
- [ ] function to multiple monthly expenese * 12 and store in annual expense state 
- [ ] function to get difference of Monthly Income - Monthly Expense and store in monthly surplus state
- [ ] function to get difference of Annual Income - Monthly Expense and store in annual surplus state
